/*
*	ALTERE TABELA_N PARA O NOME DA SUA TABELA
*	EX: SE A TABELA SE CHAMA TB_CLIENTE A TRIGGER FICARIA: TG_B_CLIENTE
*	O PREFIXO DA TABELA (TB_) É SUPRIMIDO PARA DAR ENFASE AO PREFIXO DA TRIGGER (TG_X_)
*	
*	TG_B_ - PARA TRIGGER BEFORE
*	TG_A_ - PARA TRIGGER AFTER
*/

CREATE OR REPLACE TRIGGER DATALAKE.TG_B_TABELA_N
BEFORE INSERT OR UPDATE
ON DATALAKE.TB_TABELA_N
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		:NEW.DT_INGESTAO := SYSDATE;
	ELSE
		:NEW.DT_UPDATE := SYSDATE;
	END IF;
END;